### ISSUE TITLE
How to move from a button to another tab?

### ISSUE THREAD

**Issue by yaffalhakim1** [afonsocraposo/buttons_tabbar#30]
So i made a button to move to another tab, but i don't know how to move it. Does this package have some trigger or something? Because i can't use Navigator.push or similiar

**Comment by afonsocraposo** [comment]
Hi @yaffalhakim1
Can you give me an example of what you are trying to do?

**Comment by yaffalhakim1** [comment]
so after i click this button 
![image](https://user-images.githubusercontent.com/63090705/187105841-1aebfd08-66d6-4385-ae53-e2c19fb842b4.png)
i wanna move to this tab
![image](https://user-images.githubusercontent.com/63090705/187105886-023dbbff-eb42-4593-8f5f-cf8b4cf11810.png)
how can i do that? because i cannot use navigator.push

**Comment by afonsocraposo** [comment]
This issue is not related with `buttons_tabbar`, however, to achieve what you're trying to do, I'd create a [`TabController`](https://api.flutter.dev/flutter/material/TabController-class.html) and provide it to [`ButtonsTabBar`](https://pub.dev/documentation/buttons_tabbar/latest/buttons_tabbar/ButtonsTabBar-class.html) controller [property](https://pub.dev/documentation/buttons_tabbar/latest/buttons_tabbar/ButtonsTabBar/controller.html).
Then, you could navigate to a different tab using the method [`animateTo`](https://api.flutter.dev/flutter/material/TabController/animateTo.html) from the `TabController`.

**Comment by yaffalhakim1** [comment]
thank you for the help!
