### ISSUE TITLE
[Feature] Display label text on tab selection

### ISSUE THREAD

**Issue by RoyalCoder88** [afonsocraposo/buttons_tabbar#31]
Hi, @afonsocraposo thanks for your great package, can you please add a feature to display label text only if the tab is selected, I tried with the current index page like:  ` text: _indexPagCurrent == 0 ? 'My Title' : '',` , but this way it doesn't work :( .

Thanks in advance!

**Comment by afonsocraposo** [comment]
Hi! Thank you for raising this. I'll try to check this once I have some free time 🤓

**Comment by afonsocraposo** [comment]
I've not been coding in Flutter for a while, but I'd say that the problem is you're not using `setState` when the `TabController` changes the index. Maybe you could add a listener to it and use `indexIsChanging` to properly call the `setState`:
https://api.flutter.dev/flutter/material/TabController/indexIsChanging.html
