### ISSUE TITLE
Can I add an indicator?

### ISSUE THREAD

**Issue by itMcdull** [afonsocraposo/buttons_tabbar#63]
Thank you so much

**Comment by afonsocraposo** [comment]
What?

**Comment by itMcdull** [comment]
Similar to the indicator property of Tabbar

**Comment by afonsocraposo** [comment]
Hi @itMcdull !
I'm sorry for the long wait, I'm switching jobs at the moment.
Regarding the addition of the indicator property, I don't think it makes much sense on this package, since the package already exposes parameters to control the indicator style.
Please let me know what do you want to achieve that the package is not supporting.

**Comment by afonsocraposo** [comment]
Closing this issue. Feel free to reopen it if needed
